# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {
    google = {
      source = "hashicorp/google"
      version = "5.0.0"
    }
  }
}
provider "google" {
  project     = "gcp-coe-msp-sandbox"
  region      = "europe-west1"
}
